TypeError fix
```
~/Projects/autogluon/autogluon/utils/tabular/ml/learner/default_learner.py in augment_rare_classes(self, X)
    245             new_df = new_df[:remainder]
    246             while duplicate_times > 0:
--> 247                 logger.debug("Duplicating data from rare class: " + clss)
    248                 duplicate_times -= 1
    249                 new_df = new_df.append(clss_df.copy())

TypeError: must be str, not int
```

(cherry picked from commit 32ba0d4cdeaa6e6c09302dcb639352622d499a84)